version: "3.8"
volumes:
  postgres-data:
services:
  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile.prod
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      APP_KEYS: ${APP_KEYS}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
    depends_on:
      - postgres
    ports:
      - "1337:1337"
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3000"
    depends_on:
      - strapi
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
