name: Strapi CI
on:
  push:
    paths:
      - "strapi/**"
      - ".github/workflows/strapi-ci.yml"
jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./strapi"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: yarn
          cache-dependency-path: "strapi/yarn.lock"
      - name: Install Dependencies
        run: yarn install
      - name: Production Build
        run: yarn build
